# Generated by Django 5.1.1 on 2024-12-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='customuser',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='api.hobby'),
        ),
    ]
