# Generated by Django 5.1.1 on 2025-01-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
    ]
