# Generated by Django 5.1.1 on 2025-01-17 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_pageview_remove_customuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(related_name='related_friends', through='api.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
